apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: khanation/backendimage
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: qualys-namespace
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
