version: "3.8"
services:
  mongo:
    image: mongo:7.0
    container_name: todo_mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: todo_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: todo_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:80"
    environment:
      - VUE_APP_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data:
